services:
  db:
    image: postgres:16-bookworm
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ${WEBAPP_STORAGE_HOME}/pgdata:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  web:
    image: node:22.5.1-bookworm
    depends_on:
      - db
    restart: unless-stopped
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    # puts the Dev Container on the same network as the database, so that it can access it on localhost
    network_mode: service:db