services:
  web:
    image: node:22.5.1-bookworm
    restart: unless-stopped
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/home/site/wwwroot
      - ./certs/cathedral.local.crt:/usr/local/share/ca-certificates/cathedral.local.crt
    command: /bin/sh -c "update-ca-certificates && node /home/site/wwwroot/server/index.mjs"
    ports:
      - 443:3000