// Note: it is assumed that api endpoints are snakeCaseToSlug(requirement.req_type)
// see the workbox view for a couple example usages
// TODO: update the architecture to encode this assumption somehow.
// Nuxt may limit the ability to do this, but it is worth investigating.
export enum ReqType {
    ACTOR = 'actor',
    ASSUMPTION = 'assumption',
    BEHAVIOR = 'behavior',
    COMPONENT = 'component',
    CONSTRAINT = 'constraint',
    EFFECT = 'effect',
    ENVIRONMENT_COMPONENT = 'environment_component',
    EXAMPLE = 'example',
    FUNCTIONAL_BEHAVIOR = 'functional_behavior',
    FUNCTIONALITY = 'functionality',
    GLOSSARY_TERM = 'glossary_term',
    GOAL = 'goal',
    HINT = 'hint',
    INVARIANT = 'invariant',
    JUSTIFICATION = 'justification',
    LIMIT = 'limit',
    META_REQUIREMENT = 'meta_requirement',
    NOISE = 'noise',
    NON_FUNCTIONAL_BEHAVIOR = 'non_functional_behavior',
    OBSTACLE = 'obstacle',
    ORGANIZATION = 'organization',
    OUTCOME = 'outcome',
    PARSED_REQUIREMENT = 'parsed_requirement',
    PERSON = 'person',
    PRODUCT = 'product',
    REQUIREMENT = 'requirement',
    RESPONSIBILITY = 'responsibility',
    ROLE = 'role',
    SCENARIO = 'scenario',
    SILENCE = 'silence',
    SOLUTION = 'solution',
    STAKEHOLDER = 'stakeholder',
    SYSTEM_COMPONENT = 'system_component',
    TASK = 'task',
    TEST_CASE = 'test_case',
    USE_CASE = 'use_case',
    USER_STORY = 'user_story'
}