services:
  db:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  web:
    image: node:22.5.1-bookworm
    depends_on:
      - db
    restart: unless-stopped
    # mounts the workspace folder from the local source tree into the Dev Container.
    volumes:
      - .:/workspace/cathedral:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
    networks:
      - app-network
    # puts the Dev Container on the same network as the database, so that it can access it on localhost
    # network_mode: service:db

networks:
  app-network: