services:
  db:
    image: postgres:16-bookworm
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: >
        -c ssl=on
        -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
        -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    networks:
      - app-network
  web:
    image: node:22.15.0-bookworm
    depends_on:
      - db
    restart: unless-stopped
    # mounts the workspace folder from the local source tree into the Dev Container.
    volumes:
      - .:/workspace/cathedral:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      # - 443:3000
      - 443:443
      # allows Vite to perform hot module reloading.
      - 24678:24678
    networks:
      - app-network
    # puts the Dev Container on the same network as the database, so that it can access it on localhost
    # network_mode: service:db

networks:
  app-network:

volumes:
  postgres-data:
    driver: local