
export * from './RequirementRelation.js'
export * from './Belongs.js'
export * from './Characterizes.js'
export * from './Constrains.js'
export * from './Contradicts.js'
export * from './Details.js'
export * from './Disjoins.js'
export * from './Duplicates.js'
export * from './Excepts.js'
export * from './Explains.js'
export * from './Extends.js'
export * from './Follows.js'
export * from './Repeats.js'
export * from './Shares.js'