name: Deploy Azure Infrastructure

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  # deployment:

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: azure-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # Temporary step to verify the resource group
      # It exists, but is not being seen by the next step
      - name: Verify Resource Group
        run: |
          az group show --name ${{ secrets.AZURE_RG }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Lint Bicep
        run: |
          az bicep build --file ./azure/bicep/main.bicep
      - name: Run what-if
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azure/bicep/main.bicep
          parameters: 'environment=prod '
          scope: 'resourcegroup'
          failOnStdErr: false
          additionalArguments: --what-if
  bicep-deploy:
    needs: validate
    environment: azure-prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep
        uses: azure/arm-deploy@v2
        with:
          deploymentName: ${{ github.run_number }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azure/bicep/main.bicep
          parameters: 'environment=prod '
          scope: 'resourcegroup'
          failOnStdErr: false
