# Container-based deployment to Azure Web App for Containers
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Azure Container

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: azure-prod
    permissions:
      contents: read
      packages: write # Required for GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}                    # Creates: v0.26.0 (exact version from release tag)
            type=semver,pattern={{major}}.{{minor}}            # Creates: 0.26 (major.minor version)
            type=raw,value=latest,enable={{is_default_branch}} # Creates: latest (for default branch releases)

      - name: Create environment file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "Environment file created with $(wc -l < .env) lines"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_VERSION=22.15.0
            NODE_ENV=production
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: azure-prod
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read
      id-token: write # Required for Azure federated authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Node.js for database migrations
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          cache: 'npm'

      - name: Create environment file for migrations
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "Environment file created with $(wc -l < .env) lines"

      - name: Install dependencies for migrations
        run: npm ci

      - name: Run database migrations
        run: |
          echo "Running database debug check..."
          npm run orm-debug

          echo "Listing pending migrations..."
          npm run orm-list-pending-migrations

          echo "Running pending migrations..."
          npm run orm-run-pending-migrations

          echo "Seeding users..."
          npm run orm-seed-users

          echo "Database migrations completed successfully"

      - name: Deploy to Azure Web App for Containers
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-cathedral'
          slot-name: 'Production'
          images: ghcr.io/${{ github.repository }}:${{ github.sha }}
